const SEAT_TYPE = {
    BUSINESS:'BUSINESS',
    ECONOMY:'ECONOMY',
    FIRST_CLASS:'FIRST_CLASS',
    PREMIUM_ECONOMY:'PREMIUM_ECONOMY'
}

const BOOKING_STATUS = {
    BOOKED: 'BOOKED',
    PENDING: 'PENDING',
    CANCELLED: 'CANCELLED',
    INITIATED: 'INITIATED'
}

module.exports = {
    SEAT_TYPE,
    BOOKING_STATUS
}